# Generated by Django 4.1.3 on 2022-12-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo',
            new_name='cilindrada_motor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_motor',
        ),
        migrations.AddField(
            model_name='categoria',
            name='combustible',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_vehiculo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
